In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import os
from pathlib import Path

pd.set_option('display.max_columns', None)

In [10]:
alarms_path = Path("data/alarms/alarms-240222-010325.csv")
regions_path = Path("data/alarms/regions.csv")
weather_path = Path("data/weather/all_weather_by_hour_2023-2025_v1.csv")

alarms = pd.read_csv(alarms_path, sep=";")
regions = pd.read_csv(regions_path)
weather = pd.read_csv(weather_path)

In [11]:
alarms.head()

,id,region_id,region_city,all_region,start,end
0,52432,12,Львівська обл.,1,2022-02-24 07:43:17,2022-02-24 09:52:28
1,53292,23,Чернігівська обл.,1,2022-02-24 14:00:43,2022-02-24 17:11:43
2,52080,3,Вінницька обл.,1,2022-02-24 15:40:42,2022-02-24 16:10:42
3,52857,19,Харківська обл.,1,2022-02-24 20:11:47,2022-02-24 20:59:47
4,52700,18,Тернопільська обл.,1,2022-02-25 01:59:36,2022-02-25 09:00:19

In [12]:
alarms.sample(5)

,id,region_id,region_city,all_region,start,end
43497,145125,9,Київська обл.,1,2024-07-17 22:13:41,2024-07-17 23:06:56
21446,92423,20,Херсонська обл.,1,2023-06-26 13:43:46,2023-06-26 13:53:33
31391,131716,9,Київська обл.,1,2024-01-08 06:12:06,2024-01-08 08:24:47
38966,140143,22,Черкаська обл.,1,2024-05-13 20:33:49,2024-05-13 21:54:31
35879,136677,17,Сумська обл.,1,2024-03-27 10:36:02,2024-03-27 11:03:30

In [19]:
alarms.shape

(55788, 6)

In [13]:
alarms.info()

<class 'pandas.DataFrame'>
RangeIndex: 55788 entries, 0 to 55787
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           55788 non-null  int64
 1   region_id    55788 non-null  int64
 2   region_city  55788 non-null  str
 3   all_region   55788 non-null  int64
 4   start        55788 non-null  str
 5   end          55788 non-null  str
dtypes: int64(3), str(3)
memory usage: 2.6 MB

In [20]:
regions.shape

(25, 5)

In [16]:
regions

,region,center_city_ua,center_city_en,region_alt,region_id
0,АР Крим,Сімферополь,Simferopol,Крим,1
1,Вінницька,Вінниця,Vinnytsia,Вінниччина,2
2,Волинська,Луцьк,Lutsk,Волинь,3
3,Дніпропетровська,Дніпро,Dnipro,Дніпропетровщина,4
4,Донецька,Донецьк,Donetsk,Донеччина,5
5,Житомирська,Житомир,Zhytomyr,Житомирщина,6
6,Закарпатська,Ужгород,Uzhgorod,Закарпаття,7
7,Запорізька,Запоріжжя,Zaporozhye,Запоріжжя,8
8,Івано-Франківська,Івано-Франківськ,Ivano-Frankivsk,Івано-Франківщина,9
9,Київська,Київ,Kyiv,Київщина,10
10,Кіровоградська,Кропивницький,Kropyvnytskyi,Кіровоградщина,11
11,Луганська,Луганськ,Luhansk,Луганщина,12
12,Львівська,Львів,Lviv,Львівщина,13
13,Миколаївська,Миколаїв,Mykolaiv,Миколаївщина,14
14,Одеська,Одеса,Odesa,Одещина,15
15,Полтавська,Полтава,Poltava,Полтавщина,16
16,Рівненська,Рівне,Rivne,Рівненщина,17
17,Сумська,Суми,Sumy,Сумщина,18
18,Тернопільська,Тернопіль,Ternopil,Тернопільщина,19
19,Харківська,Харків,Kharkiv,Харківщина,20
20,Херсонська,Херсон,Kherson,Херсонщина,21
21,Хмельницька,Хмельницький,Khmelnytskyi,Хмельниччина,22
22,Черкаська,Черкаси,Cherkasy,Черкащина,23
23,Чернівецька,Чернівці,Chernivtsi,Буковина,24
24,Чернігівська,Чернігів,Chernihiv,Чернігівщина,25

In [15]:
regions.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   region          25 non-null     str
 1   center_city_ua  25 non-null     str
 2   center_city_en  25 non-null     str
 3   region_alt      25 non-null     str
 4   region_id       25 non-null     int64
dtypes: int64(1), str(4)
memory usage: 1.1 KB

In [9]:
weather.head()

,city_latitude,city_longitude,city_resolvedAddress,city_address,city_timezone,city_tzoffset,day_datetime,day_datetimeEpoch,day_tempmax,day_tempmin,day_temp,day_feelslikemax,day_feelslikemin,day_feelslike,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_visibility,day_solarradiation,day_solarenergy,day_uvindex,day_sunrise,day_sunriseEpoch,day_sunset,day_sunsetEpoch,day_moonphase,day_conditions,day_description,day_icon,day_source,day_preciptype,day_stations,hour_datetime,hour_datetimeEpoch,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_preciptype,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_visibility,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions,hour_icon,hour_source,hour_stations
0,50.7469,25.3263,"Луцьк, Луцький район, Україна","Lutsk,Ukraine",Europe/Kiev,2.0,2022-02-24,1645653600,4.9,0.7,2.6,4.0,-3.1,-0.2,0.0,83.7,0.118,100.0,4.17,0.1,0.1,32.4,15.5,252.7,1022.3,72.3,12.2,36.9,2.8,1.0,07:13:36,1645679616,17:51:06,1645717866,0.77,"Snow, Partially cloudy",Partly cloudy throughout the day with morning ...,snow,obs,snow,33177099999;UKLR;remote;33301099999,00:00:00,1645653600,2.4,-1.6,89.18,0.8,0.0,0.0,0.1,0.2,['snow'],31.3,15.5,275.6,1020.0,0.0,91.5,0.0,NaN,0.0,Overcast,snow,obs,remote
1,50.7469,25.3263,"Луцьк, Луцький район, Україна","Lutsk,Ukraine",Europe/Kiev,2.0,2022-02-24,1645653600,4.9,0.7,2.6,4.0,-3.1,-0.2,0.0,83.7,0.118,100.0,4.17,0.1,0.1,32.4,15.5,252.7,1022.3,72.3,12.2,36.9,2.8,1.0,07:13:36,1645679616,17:51:06,1645717866,0.77,"Snow, Partially cloudy",Partly cloudy throughout the day with morning ...,snow,obs,snow,33177099999;UKLR;remote;33301099999,01:00:00,1645657200,2.4,-1.5,87.90,0.6,0.0,0.0,0.0,0.2,['snow'],27.7,14.8,280.3,1021.0,0.2,88.2,0.0,NaN,0.0,Partially cloudy,fog,obs,remote
2,50.7469,25.3263,"Луцьк, Луцький район, Україна","Lutsk,Ukraine",Europe/Kiev,2.0,2022-02-24,1645653600,4.9,0.7,2.6,4.0,-3.1,-0.2,0.0,83.7,0.118,100.0,4.17,0.1,0.1,32.4,15.5,252.7,1022.3,72.3,12.2,36.9,2.8,1.0,07:13:36,1645679616,17:51:06,1645717866,0.77,"Snow, Partially cloudy",Partly cloudy throughout the day with morning ...,snow,obs,snow,33177099999;UKLR;remote;33301099999,02:00:00,1645660800,2.9,-0.8,88.58,1.2,0.0,0.0,0.0,0.1,['snow'],29.2,14.4,310.0,1022.0,10.0,100.0,NaN,NaN,NaN,Overcast,cloudy,obs,33177099999
3,50.7469,25.3263,"Луцьк, Луцький район, Україна","Lutsk,Ukraine",Europe/Kiev,2.0,2022-02-24,1645653600,4.9,0.7,2.6,4.0,-3.1,-0.2,0.0,83.7,0.118,100.0,4.17,0.1,0.1,32.4,15.5,252.7,1022.3,72.3,12.2,36.9,2.8,1.0,07:13:36,1645679616,17:51:06,1645717866,0.77,"Snow, Partially cloudy",Partly cloudy throughout the day with morning ...,snow,obs,snow,33177099999;UKLR;remote;33301099999,03:00:00,1645664400,2.3,-1.3,86.63,0.3,0.0,0.0,0.0,0.1,['snow'],23.8,13.3,295.1,1021.0,0.1,92.0,0.0,NaN,0.0,Overcast,fog,obs,remote
4,50.7469,25.3263,"Луцьк, Луцький район, Україна","Lutsk,Ukraine",Europe/Kiev,2.0,2022-02-24,1645653600,4.9,0.7,2.6,4.0,-3.1,-0.2,0.0,83.7,0.118,100.0,4.17,0.1,0.1,32.4,15.5,252.7,1022.3,72.3,12.2,36.9,2.8,1.0,07:13:36,1645679616,17:51:06,1645717866,0.77,"Snow, Partially cloudy",Partly cloudy throughout the day with morning ...,snow,obs,snow,33177099999;UKLR;remote;33301099999,04:00:00,1645668000,1.9,-1.8,87.85,0.1,0.0,0.0,0.0,0.1,['snow'],24.5,13.3,305.8,1021.0,0.0,93.8,0.0,NaN,0.0,Overcast,cloudy,obs,remote

In [17]:
weather.sample(5)

,city_latitude,city_longitude,city_resolvedAddress,city_address,city_timezone,city_tzoffset,day_datetime,day_datetimeEpoch,day_tempmax,day_tempmin,day_temp,day_feelslikemax,day_feelslikemin,day_feelslike,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_visibility,day_solarradiation,day_solarenergy,day_uvindex,day_sunrise,day_sunriseEpoch,day_sunset,day_sunsetEpoch,day_moonphase,day_conditions,day_description,day_icon,day_source,day_preciptype,day_stations,hour_datetime,hour_datetimeEpoch,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_preciptype,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_visibility,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions,hour_icon,hour_source,hour_stations
42948,48.2924,25.9355,"Чернівці, Україна","Chernivtsi,Ukraine",Europe/Kiev,2.0,2022-07-08,1657227600,25.3,14.2,19.9,25.3,14.2,19.9,11.9,62.5,0.000,0.0,0.00,0.0,0.0,32.5,14.5,335.3,1017.5,67.6,24.8,268.1,23.2,9.0,05:24:31,1657247071,21:17:48,1657304268,0.30,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,obs,NaN,33658099999;15023099999;15007099999;15000099999,13:00:00,1657274400,22.9,22.9,45.74,10.6,0.0,0.0,0.0,0.0,NaN,25.3,9.4,345.0,1017.9,13.0,50.0,853.0,3.1,9.0,Partially cloudy,partly-cloudy-day,obs,15023099999;15007099999;15000099999
332673,49.4168,26.9743,"Хмельницька область, Україна","Khmelnytskyi,Ukraine",Europe/Kiev,2.0,2023-04-11,1681160400,15.1,4.6,9.6,15.1,2.6,8.6,4.5,73.3,0.100,100.0,4.17,0.0,0.0,36.4,25.2,67.7,1015.2,70.1,14.3,211.4,18.2,7.0,06:29:17,1681183757,19:58:14,1681232294,0.69,"Rain, Partially cloudy",Partly cloudy throughout the day with late aft...,rain,obs,rain,33429099999;remote,10:00:00,1681196400,7.1,4.8,84.12,4.6,0.0,0.0,0.0,0.0,NaN,25.2,11.9,56.0,1017.0,NaN,37.2,362.7,1.3,4.0,Partially cloudy,partly-cloudy-day,obs,remote
38719,46.6401,32.6142,"Херсон, Україна","Kherson,Ukraine",Europe/Kiev,2.0,2022-12-10,1670623200,13.7,6.7,11.0,13.7,5.8,10.6,10.2,94.3,1.100,100.0,16.67,0.0,0.0,38.9,25.2,170.9,1010.3,95.2,23.1,8.2,0.6,1.0,07:22:48,1670649768,16:01:41,1670680901,0.54,"Rain, Overcast",Cloudy skies throughout the day with rain in t...,rain,obs,rain,remote,07:00:00,1670648400,9.6,7.5,96.69,9.1,0.0,0.0,0.0,0.0,NaN,20.9,14.0,134.2,1011.0,0.5,99.8,0.0,NaN,0.0,Overcast,fog,obs,remote
40065,48.2924,25.9355,"Чернівці, Україна","Chernivtsi,Ukraine",Europe/Kiev,2.0,2022-03-10,1646863200,-2.4,-6.3,-4.0,-6.6,-12.2,-9.0,-7.3,78.2,1.552,100.0,33.33,1.0,1.0,54.0,21.9,6.7,1029.6,87.1,11.3,143.8,12.3,4.0,06:40:05,1646887205,18:13:53,1646928833,0.24,"Snow, Partially cloudy",Partly cloudy throughout the day with a chance...,snow,obs,snow,33658099999;15023099999;15007099999;15000099999,09:00:00,1646895600,-3.6,-8.6,90.75,-4.9,0.0,0.0,0.0,1.0,['snow'],28.8,13.9,16.0,1028.8,7.5,100.0,211.0,0.8,2.0,Overcast,cloudy,obs,15023099999;15007099999;15000099999
90061,48.0020,37.8145,"Донецьк, Україна","Donetsk,Ukraine",Europe/Kiev,2.0,2022-06-15,1655240400,21.6,15.4,18.6,21.6,15.4,18.6,14.3,77.0,7.100,100.0,25.00,0.0,0.0,37.1,16.9,312.4,1013.4,89.6,21.7,175.5,15.1,8.0,04:28:43,1655256523,20:29:58,1655314198,0.52,"Rain, Partially cloudy",Partly cloudy throughout the day with rain in ...,rain,obs,rain,remote,14:00:00,1655290800,20.2,20.2,86.63,17.9,2.9,100.0,0.0,0.0,['rain'],27.7,10.4,294.9,1013.0,12.7,100.0,130.0,0.5,1.0,"Rain, Overcast",rain,obs,remote

In [21]:
weather.shape

(608304, 65)

In [18]:
weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 608304 entries, 0 to 608303
Data columns (total 65 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   city_latitude         608304 non-null  float64
 1   city_longitude        608304 non-null  float64
 2   city_resolvedAddress  608304 non-null  str
 3   city_address          608304 non-null  str
 4   city_timezone         608304 non-null  str
 5   city_tzoffset         608304 non-null  float64
 6   day_datetime          608304 non-null  str
 7   day_datetimeEpoch     608304 non-null  int64
 8   day_tempmax           608304 non-null  float64
 9   day_tempmin           608304 non-null  float64
 10  day_temp              608304 non-null  float64
 11  day_feelslikemax      608304 non-null  float64
 12  day_feelslikemin      608304 non-null  float64
 13  day_feelslike         608304 non-null  float64
 14  day_dew               608304 non-null  float64
 15  day_humidity          608304 non-null  float64
 16  day_precip            608304 non-null  float64
 17  day_precipprob        608304 non-null  float64
 18  day_precipcover       608304 non-null  float64
 19  day_snow              608304 non-null  float64
 20  day_snowdepth         608304 non-null  float64
 21  day_windgust          608304 non-null  float64
 22  day_windspeed         608304 non-null  float64
 23  day_winddir           608304 non-null  float64
 24  day_pressure          608304 non-null  float64
 25  day_cloudcover        608304 non-null  float64
 26  day_visibility        552952 non-null  float64
 27  day_solarradiation    607752 non-null  float64
 28  day_solarenergy       607752 non-null  float64
 29  day_uvindex           607752 non-null  float64
 30  day_sunrise           608304 non-null  str
 31  day_sunriseEpoch      608304 non-null  int64
 32  day_sunset            608304 non-null  str
 33  day_sunsetEpoch       608304 non-null  int64
 34  day_moonphase         608304 non-null  float64
 35  day_conditions        608304 non-null  str
 36  day_description       608304 non-null  str
 37  day_icon              608304 non-null  str
 38  day_source            608304 non-null  str
 39  day_preciptype        342087 non-null  str
 40  day_stations          608304 non-null  str
 41  hour_datetime         608304 non-null  str
 42  hour_datetimeEpoch    608304 non-null  int64
 43  hour_temp             608304 non-null  float64
 44  hour_feelslike        608304 non-null  float64
 45  hour_humidity         608304 non-null  float64
 46  hour_dew              608304 non-null  float64
 47  hour_precip           608202 non-null  float64
 48  hour_precipprob       608304 non-null  float64
 49  hour_snow             608304 non-null  float64
 50  hour_snowdepth        608304 non-null  float64
 51  hour_preciptype       64865 non-null   str
 52  hour_windgust         608304 non-null  float64
 53  hour_windspeed        608304 non-null  float64
 54  hour_winddir          608304 non-null  float64
 55  hour_pressure         608304 non-null  float64
 56  hour_visibility       331846 non-null  float64
 57  hour_cloudcover       608304 non-null  float64
 58  hour_solarradiation   603968 non-null  float64
 59  hour_solarenergy      521042 non-null  float64
 60  hour_uvindex          603968 non-null  float64
 61  hour_conditions       608304 non-null  str
 62  hour_icon             608304 non-null  str
 63  hour_source           608304 non-null  str
 64  hour_stations         608304 non-null  str
dtypes: float64(43), int64(4), str(18)
memory usage: 301.7 MB