In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import os
from pathlib import Path

pd.set_option('display.max_columns', None)

In [2]:
alarms_path = Path("data/alarms/alarms-240222-010325.csv")
regions_path = Path("data/alarms/regions.csv")
weather_path = Path("data/weather/all_weather_by_hour_2023-2025_v1.csv")
isw_path = Path("data/isw/isw_data.json")

alarms = pd.read_csv(alarms_path, sep=";")
regions = pd.read_csv(regions_path)
weather = pd.read_csv(weather_path)
isw = pd.read_json(isw_path)

In [3]:
alarms.head()

,id,region_id,region_city,all_region,start,end
0,52432,12,Львівська обл.,1,2022-02-24 07:43:17,2022-02-24 09:52:28
1,53292,23,Чернігівська обл.,1,2022-02-24 14:00:43,2022-02-24 17:11:43
2,52080,3,Вінницька обл.,1,2022-02-24 15:40:42,2022-02-24 16:10:42
3,52857,19,Харківська обл.,1,2022-02-24 20:11:47,2022-02-24 20:59:47
4,52700,18,Тернопільська обл.,1,2022-02-25 01:59:36,2022-02-25 09:00:19

In [4]:
alarms.sample(5)

,id,region_id,region_city,all_region,start,end
24749,109630,17,Сумська обл.,1,2023-08-27 13:39:29,2023-08-27 13:52:28
26785,120705,19,Харківська обл.,1,2023-10-11 05:38:20,2023-10-11 06:12:26
55233,157991,23,Чернігівська обл.,1,2025-02-18 20:14:16,2025-02-19 05:17:30
33000,133432,19,Харківська обл.,1,2024-02-08 20:50:10,2024-02-08 21:56:46
7761,68220,19,Харківська обл.,1,2022-07-24 19:39:37,2022-07-24 19:51:35

In [5]:
alarms.shape

(55788, 6)

In [6]:
alarms.info()

<class 'pandas.DataFrame'>
RangeIndex: 55788 entries, 0 to 55787
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           55788 non-null  int64
 1   region_id    55788 non-null  int64
 2   region_city  55788 non-null  str
 3   all_region   55788 non-null  int64
 4   start        55788 non-null  str
 5   end          55788 non-null  str
dtypes: int64(3), str(3)
memory usage: 2.6 MB

In [7]:
regions.shape

(25, 5)

In [8]:
regions

,region,center_city_ua,center_city_en,region_alt,region_id
0,АР Крим,Сімферополь,Simferopol,Крим,1
1,Вінницька,Вінниця,Vinnytsia,Вінниччина,2
2,Волинська,Луцьк,Lutsk,Волинь,3
3,Дніпропетровська,Дніпро,Dnipro,Дніпропетровщина,4
4,Донецька,Донецьк,Donetsk,Донеччина,5
5,Житомирська,Житомир,Zhytomyr,Житомирщина,6
6,Закарпатська,Ужгород,Uzhgorod,Закарпаття,7
7,Запорізька,Запоріжжя,Zaporozhye,Запоріжжя,8
8,Івано-Франківська,Івано-Франківськ,Ivano-Frankivsk,Івано-Франківщина,9
9,Київська,Київ,Kyiv,Київщина,10
10,Кіровоградська,Кропивницький,Kropyvnytskyi,Кіровоградщина,11
11,Луганська,Луганськ,Luhansk,Луганщина,12
12,Львівська,Львів,Lviv,Львівщина,13
13,Миколаївська,Миколаїв,Mykolaiv,Миколаївщина,14
14,Одеська,Одеса,Odesa,Одещина,15
15,Полтавська,Полтава,Poltava,Полтавщина,16
16,Рівненська,Рівне,Rivne,Рівненщина,17
17,Сумська,Суми,Sumy,Сумщина,18
18,Тернопільська,Тернопіль,Ternopil,Тернопільщина,19
19,Харківська,Харків,Kharkiv,Харківщина,20
20,Херсонська,Херсон,Kherson,Херсонщина,21
21,Хмельницька,Хмельницький,Khmelnytskyi,Хмельниччина,22
22,Черкаська,Черкаси,Cherkasy,Черкащина,23
23,Чернівецька,Чернівці,Chernivtsi,Буковина,24
24,Чернігівська,Чернігів,Chernihiv,Чернігівщина,25

In [9]:
regions.info()

<class 'pandas.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   region          25 non-null     str
 1   center_city_ua  25 non-null     str
 2   center_city_en  25 non-null     str
 3   region_alt      25 non-null     str
 4   region_id       25 non-null     int64
dtypes: int64(1), str(4)
memory usage: 1.1 KB

In [10]:
weather.head()

,city_latitude,city_longitude,city_resolvedAddress,city_address,city_timezone,city_tzoffset,day_datetime,day_datetimeEpoch,day_tempmax,day_tempmin,day_temp,day_feelslikemax,day_feelslikemin,day_feelslike,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_visibility,day_solarradiation,day_solarenergy,day_uvindex,day_sunrise,day_sunriseEpoch,day_sunset,day_sunsetEpoch,day_moonphase,day_conditions,day_description,day_icon,day_source,day_preciptype,day_stations,hour_datetime,hour_datetimeEpoch,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_preciptype,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_visibility,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions,hour_icon,hour_source,hour_stations
0,50.7469,25.3263,"Луцьк, Луцький район, Україна","Lutsk,Ukraine",Europe/Kiev,2.0,2022-02-24,1645653600,4.9,0.7,2.6,4.0,-3.1,-0.2,0.0,83.7,0.118,100.0,4.17,0.1,0.1,32.4,15.5,252.7,1022.3,72.3,12.2,36.9,2.8,1.0,07:13:36,1645679616,17:51:06,1645717866,0.77,"Snow, Partially cloudy",Partly cloudy throughout the day with morning ...,snow,obs,snow,33177099999;UKLR;remote;33301099999,00:00:00,1645653600,2.4,-1.6,89.18,0.8,0.0,0.0,0.1,0.2,['snow'],31.3,15.5,275.6,1020.0,0.0,91.5,0.0,NaN,0.0,Overcast,snow,obs,remote
1,50.7469,25.3263,"Луцьк, Луцький район, Україна","Lutsk,Ukraine",Europe/Kiev,2.0,2022-02-24,1645653600,4.9,0.7,2.6,4.0,-3.1,-0.2,0.0,83.7,0.118,100.0,4.17,0.1,0.1,32.4,15.5,252.7,1022.3,72.3,12.2,36.9,2.8,1.0,07:13:36,1645679616,17:51:06,1645717866,0.77,"Snow, Partially cloudy",Partly cloudy throughout the day with morning ...,snow,obs,snow,33177099999;UKLR;remote;33301099999,01:00:00,1645657200,2.4,-1.5,87.90,0.6,0.0,0.0,0.0,0.2,['snow'],27.7,14.8,280.3,1021.0,0.2,88.2,0.0,NaN,0.0,Partially cloudy,fog,obs,remote
2,50.7469,25.3263,"Луцьк, Луцький район, Україна","Lutsk,Ukraine",Europe/Kiev,2.0,2022-02-24,1645653600,4.9,0.7,2.6,4.0,-3.1,-0.2,0.0,83.7,0.118,100.0,4.17,0.1,0.1,32.4,15.5,252.7,1022.3,72.3,12.2,36.9,2.8,1.0,07:13:36,1645679616,17:51:06,1645717866,0.77,"Snow, Partially cloudy",Partly cloudy throughout the day with morning ...,snow,obs,snow,33177099999;UKLR;remote;33301099999,02:00:00,1645660800,2.9,-0.8,88.58,1.2,0.0,0.0,0.0,0.1,['snow'],29.2,14.4,310.0,1022.0,10.0,100.0,NaN,NaN,NaN,Overcast,cloudy,obs,33177099999
3,50.7469,25.3263,"Луцьк, Луцький район, Україна","Lutsk,Ukraine",Europe/Kiev,2.0,2022-02-24,1645653600,4.9,0.7,2.6,4.0,-3.1,-0.2,0.0,83.7,0.118,100.0,4.17,0.1,0.1,32.4,15.5,252.7,1022.3,72.3,12.2,36.9,2.8,1.0,07:13:36,1645679616,17:51:06,1645717866,0.77,"Snow, Partially cloudy",Partly cloudy throughout the day with morning ...,snow,obs,snow,33177099999;UKLR;remote;33301099999,03:00:00,1645664400,2.3,-1.3,86.63,0.3,0.0,0.0,0.0,0.1,['snow'],23.8,13.3,295.1,1021.0,0.1,92.0,0.0,NaN,0.0,Overcast,fog,obs,remote
4,50.7469,25.3263,"Луцьк, Луцький район, Україна","Lutsk,Ukraine",Europe/Kiev,2.0,2022-02-24,1645653600,4.9,0.7,2.6,4.0,-3.1,-0.2,0.0,83.7,0.118,100.0,4.17,0.1,0.1,32.4,15.5,252.7,1022.3,72.3,12.2,36.9,2.8,1.0,07:13:36,1645679616,17:51:06,1645717866,0.77,"Snow, Partially cloudy",Partly cloudy throughout the day with morning ...,snow,obs,snow,33177099999;UKLR;remote;33301099999,04:00:00,1645668000,1.9,-1.8,87.85,0.1,0.0,0.0,0.0,0.1,['snow'],24.5,13.3,305.8,1021.0,0.0,93.8,0.0,NaN,0.0,Overcast,cloudy,obs,remote

In [11]:
weather.sample(5)

,city_latitude,city_longitude,city_resolvedAddress,city_address,city_timezone,city_tzoffset,day_datetime,day_datetimeEpoch,day_tempmax,day_tempmin,day_temp,day_feelslikemax,day_feelslikemin,day_feelslike,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_visibility,day_solarradiation,day_solarenergy,day_uvindex,day_sunrise,day_sunriseEpoch,day_sunset,day_sunsetEpoch,day_moonphase,day_conditions,day_description,day_icon,day_source,day_preciptype,day_stations,hour_datetime,hour_datetimeEpoch,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_preciptype,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_visibility,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions,hour_icon,hour_source,hour_stations
395258,48.6264,22.2851,"Ужгород, Ужгородський район, Україна","Uzhgorod,Ukraine",Europe/Uzhgorod,2.0,2024-01-31,1706652000,5.1,-4.4,-0.4,5.1,-5.5,-1.2,-3.9,78.0,0.055,100.0,4.17,0.0,7.4,22.7,7.2,150.2,1036.5,64.1,11.2,52.6,4.6,3.0,08:02:36,1706680956,17:26:31,1706714791,0.69,"Snow, Rain, Partially cloudy",Partly cloudy throughout the day with late aft...,rain,obs,rain;snow,11968099999;11933099999;11993099999;1278609999...,02:00:00,1706659200,-1.4,-1.4,84.19,-3.7,0.0,0.0,0.0,0.0,NaN,16.2,3.6,360.0,1038.8,10.0,0.0,0.0,0.0,0.0,Clear,clear-night,obs,11968099999;11933099999;11993099999;1278609999...
167226,50.9080,34.7972,"Суми, Україна","Sumy,Ukraine",Europe/Kiev,2.0,2022-03-12,1647036000,1.1,-15.4,-6.4,-1.6,-15.4,-8.2,-11.7,67.0,0.200,100.0,8.33,0.8,9.9,22.0,11.2,276.2,1026.3,51.3,15.5,149.8,12.9,5.0,06:01:48,1647057708,17:40:19,1647099619,0.31,"Snow, Partially cloudy",Partly cloudy throughout the day with late aft...,snow,obs,snow,34202099999;33275099999;remote,18:00:00,1647100800,-1.6,-1.6,67.66,-6.8,0.0,0.0,0.0,9.2,['snow'],8.6,2.9,327.8,1024.0,4.2,100.0,124.0,0.4,0.0,Overcast,cloudy,obs,remote
4617,50.7469,25.3263,"Луцьк, Луцький район, Україна","Lutsk,Ukraine",Europe/Kiev,2.0,2022-09-04,1662238800,19.2,7.7,13.6,19.2,7.7,13.6,8.6,75.4,0.000,0.0,0.00,0.0,0.0,20.9,10.8,97.5,1024.1,72.7,19.5,199.5,17.2,7.0,06:36:48,1662262608,19:57:46,1662310666,0.25,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,obs,NaN,33177099999;remote;33301099999,10:00:00,1662274800,12.6,12.6,90.58,11.1,0.0,0.0,0.0,0.0,NaN,9.7,4.0,97.9,1025.0,24.1,53.4,382.0,1.4,4.0,Partially cloudy,partly-cloudy-day,obs,remote
566031,49.2336,28.4486,"Вінниця, Україна","Vinnytsia,Ukraine",Europe/Kiev,2.0,2024-07-25,1721854800,22.6,17.4,19.6,22.6,17.4,19.6,16.9,84.7,2.000,100.0,4.17,0.0,0.0,25.2,14.4,93.1,1008.6,87.4,10.0,126.8,11.0,4.0,05:29:27,1721874567,20:55:21,1721930121,0.64,"Rain, Partially cloudy",Partly cloudy throughout the day with late aft...,rain,obs,rain,33562099999;remote,16:00:00,1721912400,20.9,20.9,77.40,16.8,0.0,0.0,0.0,0.0,NaN,24.5,4.7,94.9,1008.0,NaN,74.4,330.1,1.2,3.0,Partially cloudy,partly-cloudy-day,obs,remote
283249,48.4753,35.0160,"Дніпро, Україна","Dnipro,Ukraine",Europe/Kiev,2.0,2023-12-21,1703109600,7.1,2.7,5.4,5.8,0.3,3.2,4.4,92.8,0.200,100.0,8.33,0.0,0.3,37.4,25.2,205.3,1004.4,98.4,5.1,12.2,1.1,1.0,07:28:53,1703136533,15:46:52,1703166412,0.30,"Rain, Overcast",Cloudy skies throughout the day with afternoon...,rain,obs,rain,34504099999;remote,01:00:00,1703113200,6.5,2.9,92.04,5.3,0.0,0.0,0.0,0.0,NaN,37.1,20.5,191.9,1008.0,NaN,83.4,0.0,0.0,0.0,Partially cloudy,partly-cloudy-night,obs,remote

In [12]:
weather.shape

(608304, 65)

In [13]:
weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 608304 entries, 0 to 608303
Data columns (total 65 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   city_latitude         608304 non-null  float64
 1   city_longitude        608304 non-null  float64
 2   city_resolvedAddress  608304 non-null  str
 3   city_address          608304 non-null  str
 4   city_timezone         608304 non-null  str
 5   city_tzoffset         608304 non-null  float64
 6   day_datetime          608304 non-null  str
 7   day_datetimeEpoch     608304 non-null  int64
 8   day_tempmax           608304 non-null  float64
 9   day_tempmin           608304 non-null  float64
 10  day_temp              608304 non-null  float64
 11  day_feelslikemax      608304 non-null  float64
 12  day_feelslikemin      608304 non-null  float64
 13  day_feelslike         608304 non-null  float64
 14  day_dew               608304 non-null  float64
 15  day_humidity          608304 non-null  float64
 16  day_precip            608304 non-null  float64
 17  day_precipprob        608304 non-null  float64
 18  day_precipcover       608304 non-null  float64
 19  day_snow              608304 non-null  float64
 20  day_snowdepth         608304 non-null  float64
 21  day_windgust          608304 non-null  float64
 22  day_windspeed         608304 non-null  float64
 23  day_winddir           608304 non-null  float64
 24  day_pressure          608304 non-null  float64
 25  day_cloudcover        608304 non-null  float64
 26  day_visibility        552952 non-null  float64
 27  day_solarradiation    607752 non-null  float64
 28  day_solarenergy       607752 non-null  float64
 29  day_uvindex           607752 non-null  float64
 30  day_sunrise           608304 non-null  str
 31  day_sunriseEpoch      608304 non-null  int64
 32  day_sunset            608304 non-null  str
 33  day_sunsetEpoch       608304 non-null  int64
 34  day_moonphase         608304 non-null  float64
 35  day_conditions        608304 non-null  str
 36  day_description       608304 non-null  str
 37  day_icon              608304 non-null  str
 38  day_source            608304 non-null  str
 39  day_preciptype        342087 non-null  str
 40  day_stations          608304 non-null  str
 41  hour_datetime         608304 non-null  str
 42  hour_datetimeEpoch    608304 non-null  int64
 43  hour_temp             608304 non-null  float64
 44  hour_feelslike        608304 non-null  float64
 45  hour_humidity         608304 non-null  float64
 46  hour_dew              608304 non-null  float64
 47  hour_precip           608202 non-null  float64
 48  hour_precipprob       608304 non-null  float64
 49  hour_snow             608304 non-null  float64
 50  hour_snowdepth        608304 non-null  float64
 51  hour_preciptype       64865 non-null   str
 52  hour_windgust         608304 non-null  float64
 53  hour_windspeed        608304 non-null  float64
 54  hour_winddir          608304 non-null  float64
 55  hour_pressure         608304 non-null  float64
 56  hour_visibility       331846 non-null  float64
 57  hour_cloudcover       608304 non-null  float64
 58  hour_solarradiation   603968 non-null  float64
 59  hour_solarenergy      521042 non-null  float64
 60  hour_uvindex          603968 non-null  float64
 61  hour_conditions       608304 non-null  str
 62  hour_icon             608304 non-null  str
 63  hour_source           608304 non-null  str
 64  hour_stations         608304 non-null  str
dtypes: float64(43), int64(4), str(18)
memory usage: 301.7 MB

In [14]:
isw.head()

,date,title,url,key_takeaways
0,2026-03-05,"Russian Offensive Campaign Assessment, March 5...",https://understandingwar.org/research/russia-u...,[Ukrainian President Volodymyr Zelensky announ...
1,2026-03-05,"Russian Occupation Update, March 5, 2026",https://understandingwar.org/research/russia-u...,[Russia is facilitating the admission of Ukrai...
2,2026-03-04,"Russian Offensive Campaign Assessment, March 4...",https://understandingwar.org/research/russia-u...,[Ukrainian forces damaged a Russian frigate an...
3,2026-03-03,"Russian Offensive Campaign Assessment, March 3...",https://understandingwar.org/research/russia-u...,[The United States and Israel are striking Ira...
4,2026-03-02,"Russian Offensive Campaign Assessment, March 2...",https://understandingwar.org/research/russia-u...,[Russian President Vladimir Putin is attemptin...

In [16]:
isw.shape

(2102, 4)